# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "centos/stream8"
MEM = 1024
CPU = 1

MASTER_NAME="smakniS"

MASTER_IP = "192.168.42.110"

setup_master = <<-SHELL
  echo "** Setup Master **"
  sudo -i
  export K3S_NODE_NAME=$MASTER_NAME
  export K3S_KUBECONFIG_MODE=644
  export INSTALL_K3S_EXEC="server --bind-address=#{MASTER_IP} --node-ip=#{MASTER_IP}  --flannel-iface=eth1"
  echo "** Install K3S **"
  curl -sfL https://get.k3s.io | sh -
  echo "** Waiting install **"
  sleep 20
  echo "** Install net tools **"
  sudo yum -y install net-tools
  echo "** Install cluster **"
  /usr/local/bin/kubectl apply -f /vagrant/kube
  echo "** Setup Master complete **"
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  config.vm.box_check_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true } # VirtualBox Guest Additions: to enable vboxsf (synched folder)
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEM
    vb.cpus = CPU
  end

  config.vm.define MASTER_NAME, primary: true do |master|
    master.vm.hostname = MASTER_NAME
    master.vm.network "private_network", ip: MASTER_IP
    master.vm.provider "virtualbox" do |vb|
			vb.name = MASTER_NAME
		end
    master.vm.provision "shell", inline: setup_master
  end
end